# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    # apt: "puppetlabs/apt"
    facts: "puppetlabs/facts"
    nginx: "puppet/nginx"
    puppet_agent: "puppetlabs/puppet_agent"
    # service: "puppetlabs/service"
    stdlib: "puppetlabs/stdlib"
    yumrepo: "puppetlabs/yumrepo_core"
  repositories:
    provision: 'https://github.com/puppetlabs/provision.git'
    # puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'